import Link from 'next/link'
import { ArrowRight, Check, ShieldCheck } from 'lucide-react'
import { Container } from '@/components/ui/Container'
import { Button } from '@/components/ui/Button'
import { FAQ } from '@/components/ui/FAQ'
import { CarrierApplicationForm } from './CarrierApplicationForm'
import { ServicePlanCard } from './ServicePlanCard'
import { networkDisclaimer, networkFaqs, services } from '@/lib/carrier-network'
import type { PlanId } from '@/lib/carrier-network'

const faqItems = networkFaqs.map(item => ({ question: item.question, answer: item.answer }))

export function ServiceLanding() {
  return <main>
    <section className="relative overflow-hidden bg-navy py-16 text-white sm:py-24"><div className="absolute inset-y-0 right-0 hidden w-1/2 bg-[radial-gradient(ellipse_at_top_right,rgba(6,182,212,.22),transparent_60%)] lg:block" /><Container><div className="relative max-w-4xl"><p className="mb-4 text-sm font-bold uppercase tracking-[.18em] text-cyan">FreightSync Carrier Network</p><h1 className="text-4xl font-extrabold leading-tight text-white sm:text-5xl lg:text-6xl">One network for the work behind every mile.</h1><p className="mt-6 max-w-3xl text-lg leading-relaxed text-white/80">Choose the level of transportation technology and operational support that fits your business today. Start with the tools, add support as you grow.</p><div className="mt-8 flex flex-wrap gap-3"><Button href="/get-started?source=services" size="lg" variant="teal">Explore your fit</Button><Button href="/pricing" size="lg" variant="outline" className="border-white/50 text-white hover:bg-white hover:text-navy">Compare pricing</Button></div><p className="mt-5 max-w-2xl text-sm text-white/60">{networkDisclaimer}</p></div></Container></section>
    <section className="bg-muted py-14 sm:py-20"><Container><div className="mx-auto max-w-3xl text-center"><p className="text-sm font-bold uppercase tracking-[.16em] text-cyan">Choose your support</p><h2 className="mt-3 text-3xl font-extrabold text-navy sm:text-4xl">Three ways to work with FreightSync</h2><p className="mt-4 text-neutral">Each service is built on practical tools for transportation operators—not a promise of freight, placements, or revenue.</p></div><div className="mt-10 grid gap-6 lg:grid-cols-3 lg:grid-rows-[repeat(10,auto)] lg:gap-y-0">{services.map((service,index)=><ServicePlanCard key={service.id} service={service} index={index} source="Services" featureCount={6} tone="gradient" primaryAction="details" />)}</div></Container></section>
    <section className="bg-white py-14 sm:py-20"><Container><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-sm font-bold uppercase tracking-[.16em] text-cyan">At a glance</p><h2 className="mt-3 text-3xl font-extrabold text-navy">Support that scales with your operation.</h2><p className="mt-4 leading-relaxed text-neutral">Start where you are. Select the service that reflects how much day-to-day help you need; no setup fee, no cancellation fee, cancel anytime.</p><Link href="/pricing" className="mt-5 inline-flex items-center gap-2 font-semibold text-cyan hover:text-navy">See full comparison<ArrowRight className="h-4 w-4" /></Link></div><div className="grid gap-3 sm:grid-cols-2">{['A connected TMS and carrier profile','Shared visibility for documents and activity','Human support when operations need it','Admin-reviewed network matching only'].map(item=><div key={item} className="flex items-start gap-3 rounded-xl border border-border bg-muted/60 p-4"><ShieldCheck className="h-5 w-5 shrink-0 text-cyan" /><p className="font-semibold text-navy">{item}</p></div>)}</div></div></Container></section>
    <section className="bg-muted py-14 sm:py-20"><Container><div className="mx-auto max-w-3xl"><p className="text-center text-sm font-bold uppercase tracking-[.16em] text-cyan">Questions, answered</p><h2 className="mb-8 mt-3 text-center text-3xl font-extrabold text-navy">Carrier Network FAQ</h2><FAQ items={faqItems} /></div></Container></section>
    <section className="bg-white py-14 sm:py-20"><Container><div className="mx-auto mb-10 max-w-3xl text-center"><p className="text-sm font-bold uppercase tracking-[.16em] text-cyan">Start a conversation</p><h2 className="mt-3 text-3xl font-extrabold text-navy sm:text-4xl">Tell us what your operation needs.</h2><p className="mt-4 text-neutral">A short application helps our team understand where to begin. Submission is not account activation; every network match is reviewed by FreightSync.</p></div><div className="mx-auto max-w-3xl"><CarrierApplicationForm source="Services" /></div></Container></section>
  </main>
}

export function ServiceDetail({ slug }: { slug: string }) {
  const service = services.find(item => item.slug === slug)
  if (!service) return <section className="py-24"><Container><h1 className="text-4xl font-bold text-navy">Service not found</h1><Button href="/services" className="mt-6">View services</Button></Container></section>
  const audienceTitle = service.id === 'connect' ? 'For independent operators who need a better home base.' : service.id === 'dispatch' ? 'For carriers who want dispatch help without losing control.' : 'For owners coordinating people, vehicles, and freight.'
  const audienceCopy = service.id === 'connect' ? 'Independent drivers, vehicle owners, and small fleets can organize the moving parts of their transportation business with a shared profile, documents, and TMS tools.' : service.id === 'dispatch' ? 'Owner operators and independent carriers can ask for hands-on support with load discovery, broker communication, and delivery coordination.' : 'Vehicle owners and growing fleets can bring day-to-day coordination, reporting, and operational support into one workflow.'
  return <main>
    <section className="bg-navy py-16 text-white sm:py-24"><Container><p className="mb-4 text-sm font-bold uppercase tracking-[.18em] text-cyan">FreightSync Carrier Network / {service.name}</p><div className="grid gap-10 lg:grid-cols-[1.15fr_.85fr] lg:items-center"><div><h1 className="text-4xl font-extrabold leading-tight text-white sm:text-5xl">{service.headline}</h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-white/80">{service.description}</p><div className="mt-8 flex flex-wrap gap-3"><Button href="#application-form" variant="teal" size="lg">{service.cta}</Button><Button href="/pricing" variant="outline" size="lg" className="border-white/50 text-white hover:bg-white hover:text-navy">Compare plans</Button></div></div><div className="rounded-2xl border border-white/15 bg-white/10 p-6 backdrop-blur"><p className="text-sm font-bold uppercase tracking-wide text-cyan">Straightforward pricing</p><p className="mt-3 text-3xl font-extrabold">{service.price}</p><p className="mt-2 leading-relaxed text-white/75">{service.trial}</p><div className="mt-5 border-t border-white/15 pt-4 text-sm text-white/75">{service.feeScope}</div></div></div></Container></section>
    <section className="bg-white py-14 sm:py-20"><Container><div className="grid gap-12 lg:grid-cols-2"><div><p className="text-sm font-bold uppercase tracking-[.16em] text-cyan">Who it is for</p><h2 className="mt-3 text-3xl font-extrabold text-navy">{audienceTitle}</h2><p className="mt-5 leading-relaxed text-neutral">{audienceCopy}</p>{service.id === 'dispatch' && <p className="mt-4 rounded-xl border-l-4 border-cyan bg-cyan/5 p-4 font-semibold leading-relaxed text-navy">We succeed when you succeed. FreightSync’s dispatch fee is tied directly to the freight we help you move.</p>}<p className="mt-4 leading-relaxed text-neutral">FreightSync provides transportation technology, carrier support, and dispatch-related services under the applicable customer agreement. Freight availability and revenue are not guaranteed.</p></div><div className="rounded-2xl bg-muted p-6 sm:p-8"><p className="text-sm font-bold uppercase tracking-[.16em] text-cyan">Included support</p><ul className="mt-5 grid gap-3 sm:grid-cols-2">{service.features.map(feature=><li key={feature} className="flex gap-2 text-sm text-neutral"><Check className="h-4 w-4 shrink-0 text-teal" />{feature}</li>)}</ul></div></div></Container></section>
    <section className="bg-muted py-14 sm:py-20"><Container><div className="mx-auto max-w-3xl"><h2 className="mb-8 text-center text-3xl font-extrabold text-navy">Common questions</h2><FAQ items={faqItems} /></div></Container></section>
    <section className="bg-white py-14 sm:py-20"><Container><div className="mx-auto mb-10 max-w-3xl text-center"><p className="text-sm font-bold uppercase tracking-[.16em] text-cyan">Your next step</p><h2 className="mt-3 text-3xl font-extrabold text-navy">Let’s see if {service.name.replace('FreightSync ','')} fits.</h2><p className="mt-4 text-neutral">Share a few details. Our team will review your application and follow up—there is no automatic account activation.</p></div><div className="mx-auto max-w-3xl"><CarrierApplicationForm initialPlan={service.id as PlanId} source={service.name} /></div></Container></section>
  </main>
}
